### PR TITLE
improve:

### PR DESCRIPTION
**Pull request by cuongdevjs**
- add function convert RGBA to hex

### CODE REVIEW

**Comment by wangzuo** [comment]
we use prettier with single quote, please update the pr and avoid meaningless changes.

**Comment by cuongdevjs** [comment]
can 

> we use prettier with single quote, please update the pr and avoid meaningless changes.

can you update the convention code?

**Comment by wangzuo** [comment]
yes, just added the `prettier.config.js` file

**Comment by cuongdevjs** [comment]
> we use prettier with single quote, please update the pr and avoid meaningless changes.

I just updated new commit. You can review it 😄

**Comment by wangzuo** [comment]
Thank you, will check it

**Comment by wangzuo** [comment]
I made some change based on your pr and released it in `4.0.0`, let me know for any issue

**Pull request merged**
